[package]
name = "paypal"
version = "0.0.0"
authors = ["nikos <nikos@mugsoft.io>"]
edition = "2018"
description = "A library to communicate with paypal api"
license = "MIT"
repository = "https://github.com/nikosEfthias/paypal"
[dependencies]
